apiVersion: batch/v1
kind: Job
metadata:
  name: rails-migrations
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: rails-app
        image: ministryofjustice/cloud-platform-multi-container-demo-app:rails-app-1.6
        command: [ "bundle", "exec", "rails", "db:migrate" ]
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: rds-instance-multi-container-demo-dev
                key: url
      restartPolicy: OnFailure
